DROP TABLE IF EXISTS events;

CREATE TABLE events (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    weekday TEXT,
    event TEXT,
    date_created TIMESTAMP NOT NULL DEFAULT now(),
    user_id INTEGER
        REFERENCES this_week_users(id) ON DELETE CASCADE NOT NULL
);